procesamientonomina:
  paths:
    input: "src/main/resources/input/empleados.csv"
    valid-output: "src/main/resources/output/validos.csv"
    invalid-output: "src/main/resources/output/invalidos.csv"
